
default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  username: rails_user
    password: rail$!pa$$w0rd11


development:
  primary:
    <<: *default
    database: inservpro_dev
    host: 192.168.210.86
  vicidial:
    <<: *default
    database: asterisk
    host: 10.78.9.155
    database_tasks: false


test:
  primary:
    <<: *default
    database: inservpro_test
    host: 192.168.210.86
  vicidial:
    <<: *default
    database: asterisk
    host: 10.78.9.155
    database_tasks: false


production:
  primary:
    <<: *default
    database: inservpro
    host: 192.168.210.86
  vicidial:
    <<: *default
    database: asterisk
    host: 10.78.9.155
    database_tasks: false